version: 5.8.x.{build}
os: Visual Studio 2015
environment:
  matrix:
  - {}
build_script:
- cmd: >-
    mkdir build
    cd build
    cmake .. -G "Visual Studio 14"
    cmake --build . 
test_script:
- cmd: ctest
